version: '3'

services:

  nginx:
    build:
      context: .build/docker/nginx
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - ./.build/docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.build/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - internal_ipoteka_back

  php:
    build:
      context: .build/docker/php
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./:/app
      - ~/.ssh:/home/www-data/.ssh
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    networks:
      - internal_ipoteka_back

  db:
    image: mysql:5.7
    command: --max_allowed_packet=100M --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./:/app
      - internal_ipoteka_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ipoteka
      MYSQL_USER: ipoteka
      MYSQL_PASSWORD: ipoteka
    ports:
      - '3306:3306'
    networks:
      - internal_ipoteka_back

volumes:
  internal_ipoteka_mysql_data:

networks:
  internal_ipoteka_back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28